### ISSUE TITLE
package:discover returns null

### ISSUE THREAD

**Issue by tylerwiegand** [yaquawa/laravel-email-reset#1]
Just composer required, and got this. I followed the instructions for installation and the package works, but the stubbed controller generated with the publish command doesn't work as intended. Thankfully, I copied and pasted your documented controller and that one works fine.

It kept complaining that "$new_email" OR "$email" wasn't defined, but the reset always successfully took place.

Good package overall, really didn't wanna do this logic myself. Woo!

```
composer require yaquawa/laravel-email-reset
Using version ^1.0 for yaquawa/laravel-email-reset
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing yaquawa/laravel-token-repository (v1.0.1): Downloading (100%)
  - Installing yaquawa/laravel-email-reset (v1.0.4): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Config.php line 16:

  Return value of Yaquawa\Laravel\EmailReset\Config::driverConfig() must be o
  f the type array, null returned


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by yaquawa** [comment]
Try this and see if it'll work:

Add the following code to your <config/auth.php> file.

```
'defaults' => [
    'guard'       => 'web',
    'passwords'   => 'users',
    'email-reset' => 'default' // Add this line
],

// Add this entire block
'email-reset' => [
    'default' => [
        'table'  => 'email_resets',
        'expire' => 60,
        // 'ignore-migrations' => true,
        // 'route' => 'email/reset/{token}',
    ]
]
```

**Comment by tylerwiegand** [comment]
Yes, that's part of your instructions, which I stated above that I followed. The package works, I just had to drop in the controller logic posted in the readme and NOT the published stub.

Also, the autodiscovery didn't work when I composer installed.

Are you saying to add the array into the auth.php config PRIOR to composer installing? If so, you may want to amend your readme to reflect that change.

**Comment by hirbod** [comment]
@yaquawa I also have the same issue. And I already added that stuff to my auth, even before the setup.. Still throwing that issue

**Comment by hirbod** [comment]
I had to totally remove everything, add the serviceProvider upfront, now it worked

**Comment by abenevaut** [comment]
@yaquawa could be closed

**Comment by tylerwiegand** [comment]
Really? Do nothing then close it? Not even a response?

**Comment by yaquawa** [comment]
@tylerwiegand I couldn't reproduce the issue, everything goes fine.. 
@abenevaut Can you reproduce the issue??

**Comment by abenevaut** [comment]
Sorry guys, i saw the date and then no follow-up since, I told myself that you were moving on to something else.

I can reproduce the error during composer install, it's happen **only** if i install the vendor without the required configurations in `auth.php`. If i install the vendor in a fresh project **with** the required configuration in `auth.php`, it's work fine.

And you got it @tylerwiegand ..
> Are you saying to add the array into the auth.php config PRIOR to composer installing? If so, you may want to amend your readme to reflect that change.

I'll propose a PR for the readme.

**Comment by yaquawa** [comment]
@abenevaut Thanks for your feedback🖐🏼

**Comment by abenevaut** [comment]
@tylerwiegand @Hirbod @yaquawa curious to know your opinions on PR https://github.com/yaquawa/laravel-email-reset/pull/6, which aims to correct the dilemma encountered in this issue.

**Comment by hirbod** [comment]
I did not use this package at the end and developed an workaround but I might give it another shot once the package is ready for laravel 7 and 8
