### ISSUE TITLE
Error when use with PostgresQL

### ISSUE THREAD

**Issue by riztter** [yaquawa/laravel-email-reset#2]
This error is show when I use with PostgresQL
`SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for uuid: "1" (SQL: delete from "email_resets" where "user_id" = 1)`
Can someone help me.
Thank.

**Comment by yaquawa** [comment]
@riztter 
The migration seems to be causing the problem, try editing the [migration file](https://github.com/yaquawa/laravel-email-reset/blob/master/database/migrations/2018_06_01_000001_create_email_resets_table.php#L17):

```php
$table->uuid('user_id')->primary();
```

**Comment by riztter** [comment]
@yaquawa 
Edit to what ?

**Comment by yaquawa** [comment]
the type of your `user_id`, probably the `bigIncrements`

```sql
$table->bigIncrements('user_id');
```
